name: Run PostgreSQL Database Migrations

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up PostgreSQL (local or external)
      run: |
        echo "Setting up PostgreSQL connection"
    
    - name: Run SQL Migration Scripts
      run: |
        for migration in ./migrations/*.sql; do
          echo "Running migration: $migration"
          psql -h ${{ secrets.PG_HOST }} -U ${{ secrets.PG_USER }} -d ${{ secrets.PG_DB }} -a -f $migration
        done
      env:
        PG_HOST: ${{ secrets.PG_HOST }}
        PG_PORT: 5432
        PG_DB: ${{ secrets.PG_DB }}
        PG_USER: ${{ secrets.PG_USER }}
        PG_PASSWORD: ${{ secrets.PG_PASSWORD }}

    - name: Success
      run: echo "Database migrations completed successfully!"
