name: Run PostgreSQL Database Setup and Migrations

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (adjust to your default branch)
  pull_request:
    branches:
      - main  

jobs:
  setup-and-migrate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up PostgreSQL using Docker
      uses: docker://postgres:latest
      env:
        POSTGRES_DB: ${{ secrets.PG_DB }}
        POSTGRES_USER: ${{ secrets.PG_USER }}
        POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
      with:
        entrypoint: "/bin/bash -c 'while ! pg_isready -h localhost -p 5432; do sleep 1; done; exec docker-entrypoint.sh postgres'"
    
    - name: Run SQL Migration Scripts (Optional)
      run: |
        # Assuming you have SQL migration files in the `migrations` folder
        psql -h localhost -U ${{ secrets.PG_USER }} -d ${{ secrets.PG_DB }} -f ./migrations/your_migration_script.sql
      env:
        PG_HOST: localhost
        PG_PORT: 5432
        PG_DB: ${{ secrets.PG_DB }}
        PG_USER: ${{ secrets.PG_USER }}
        PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
    
    - name: Success
      run: echo "Database migration and setup completed successfully!"
